"""create baseline schema

Revision ID: baseline_0001
Revises:
Create Date: 2026-09-26 20:57:36.724156
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "baseline_0001"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

# This baseline replaces the pre-2026-09-26 migration chain. Databases created
# before it cannot be upgraded; drop and recreate them (see README).


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("wallet_address", sa.String(length=42), nullable=True),
        sa.Column(
            "account_type", sa.String(length=10), server_default=sa.text("'human'"), nullable=False
        ),
        sa.Column("is_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "display_name",
            sa.String(length=255),
            server_default=sa.text("'Anonymous'"),
            nullable=False,
        ),
        sa.Column("nonce", sa.String(length=64), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "nonce_issued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("token_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("wallet_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pending_wallet_address", sa.String(length=42), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
    )
    op.create_index(op.f("ix_accounts_wallet_address"), "accounts", ["wallet_address"], unique=True)
    op.create_table(
        "services",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("provider_account_id", sa.BigInteger(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "lifecycle",
            sa.Enum(
                "draft",
                "active",
                "suspended",
                "delisted",
                name="service_lifecycle",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("current_revision_id", sa.BigInteger(), nullable=True),
        sa.Column("current_change_token", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["provider_account_id"],
            ["accounts.id"],
            name=op.f("fk_services_provider_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
        sa.UniqueConstraint("slug", name=op.f("uq_services_slug")),
    )
    op.create_index(
        op.f("ix_services_provider_account_id"), "services", ["provider_account_id"], unique=False
    )
    op.create_table(
        "service_revisions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("service_id", sa.BigInteger(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("change_token", sa.String(length=64), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_service_revisions_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_revisions")),
        sa.UniqueConstraint(
            "service_id", "revision_number", name=op.f("uq_service_revisions_service_id")
        ),
    )
    op.create_index(
        op.f("ix_service_revisions_service_id"), "service_revisions", ["service_id"], unique=False
    )
    # services.current_revision_id and service_revisions.service_id form a genuine
    # two-table cycle, so the FK back to service_revisions is added only once both
    # tables exist (matching how service_revisions_0004 did this in the old chain).
    op.create_foreign_key(
        op.f("fk_services_current_revision_id_service_revisions"),
        "services",
        "service_revisions",
        ["current_revision_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("key_prefix", sa.String(length=32), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_api_keys_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_api_keys_key_hash")),
    )
    op.create_index(op.f("ix_api_keys_account_id"), "api_keys", ["account_id"], unique=False)
    op.create_table(
        "moderation_actions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("service_id", sa.BigInteger(), nullable=False),
        sa.Column("actor_account_id", sa.BigInteger(), nullable=True),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('suspend', 'restore', 'delist')",
            name=op.f("ck_moderation_actions_action_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_account_id"],
            ["accounts.id"],
            name=op.f("fk_moderation_actions_actor_account_id_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_moderation_actions_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_moderation_actions")),
    )
    op.create_index(
        "ix_moderation_actions_service_id_id_desc",
        "moderation_actions",
        ["service_id", sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_table(
        "service_endpoints",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("service_id", sa.BigInteger(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "access_mode",
            sa.Enum("free", "paid", name="access_mode", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("request_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("response_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_service_endpoints_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_endpoints")),
        sa.UniqueConstraint("service_id", "key", name=op.f("uq_service_endpoints_service_id")),
    )
    op.create_index(
        op.f("ix_service_endpoints_service_id"), "service_endpoints", ["service_id"], unique=False
    )
    op.create_table(
        "service_health_checks",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("service_id", sa.BigInteger(), nullable=False),
        sa.Column("check_name", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pass",
                "fail",
                "error",
                name="service_health_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_service_health_checks_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_health_checks")),
    )
    op.create_index(
        "ix_service_health_checks_service_id_check_name_checked_at",
        "service_health_checks",
        ["service_id", "check_name", "checked_at"],
        unique=False,
    )
    op.create_table(
        "service_tags",
        sa.Column("service_id", sa.BigInteger(), nullable=False),
        sa.Column("tag", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_service_tags_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("service_id", "tag", name=op.f("pk_service_tags")),
    )
    op.create_table(
        "wallet_change_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("previous_wallet_address", sa.String(length=42), nullable=False),
        sa.Column("new_wallet_address", sa.String(length=42), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_wallet_change_log_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallet_change_log")),
    )
    op.create_index(
        op.f("ix_wallet_change_log_account_id"), "wallet_change_log", ["account_id"], unique=False
    )
    op.create_table(
        "endpoint_prices",
        sa.Column("endpoint_id", sa.BigInteger(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount_minor > 0", name=op.f("ck_endpoint_prices_positive_amount_minor")
        ),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["service_endpoints.id"],
            name=op.f("fk_endpoint_prices_endpoint_id_service_endpoints"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("endpoint_id", name=op.f("pk_endpoint_prices")),
    )
    op.create_table(
        "provider_upstreams",
        sa.Column("endpoint_id", sa.BigInteger(), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("http_method", sa.String(length=16), nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["service_endpoints.id"],
            name=op.f("fk_provider_upstreams_endpoint_id_service_endpoints"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("endpoint_id", name=op.f("pk_provider_upstreams")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("provider_upstreams")
    op.drop_table("endpoint_prices")
    op.drop_index(op.f("ix_wallet_change_log_account_id"), table_name="wallet_change_log")
    op.drop_table("wallet_change_log")
    op.drop_table("service_tags")
    op.drop_index(
        "ix_service_health_checks_service_id_check_name_checked_at",
        table_name="service_health_checks",
    )
    op.drop_table("service_health_checks")
    op.drop_index(op.f("ix_service_endpoints_service_id"), table_name="service_endpoints")
    op.drop_table("service_endpoints")
    op.drop_index("ix_moderation_actions_service_id_id_desc", table_name="moderation_actions")
    op.drop_table("moderation_actions")
    op.drop_index(op.f("ix_api_keys_account_id"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_constraint(
        op.f("fk_services_current_revision_id_service_revisions"), "services", type_="foreignkey"
    )
    op.drop_index(op.f("ix_service_revisions_service_id"), table_name="service_revisions")
    op.drop_table("service_revisions")
    op.drop_index(op.f("ix_services_provider_account_id"), table_name="services")
    op.drop_table("services")
    op.drop_index(op.f("ix_accounts_wallet_address"), table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
